# Generated by Django 3.2 on 2024-01-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='We usualy order a model in a client and an admin part.', verbose_name='Sorting')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Show when an entry was created.', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Show when an entry was updated', null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, help_text='This entry is visible or unvisible for a client part or admin part.', verbose_name='Public')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete status')),
                ('text', models.TextField(verbose_name='comment for petition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='We usualy order a model in a client and an admin part.', verbose_name='Sorting')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Show when an entry was created.', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Show when an entry was updated', null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, help_text='This entry is visible or unvisible for a client part or admin part.', verbose_name='Public')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='We usualy order a model in a client and an admin part.', verbose_name='Sorting')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Show when an entry was created.', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Show when an entry was updated', null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, help_text='This entry is visible or unvisible for a client part or admin part.', verbose_name='Public')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='We usualy order a model in a client and an admin part.', verbose_name='Sorting')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Show when an entry was created.', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Show when an entry was updated', null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, help_text='This entry is visible or unvisible for a client part or admin part.', verbose_name='Public')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete status')),
                ('title', models.CharField(max_length=255, verbose_name='Title of petition')),
                ('description', models.TextField(verbose_name='Description of petition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
