# Generated by Django 3.2 on 2024-01-19 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User created petition'),
        ),
        migrations.AddField(
            model_name='likes',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.petition', verbose_name='Petition liked by user'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User liked petition'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.petition', verbose_name='Petition disliked by user'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User disliked petition'),
        ),
        migrations.AddField(
            model_name='comment',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.petition', verbose_name='Petition commented by user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User commented petition'),
        ),
    ]
